In [66]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#distance calculations
from geopy.distance import great_circle
from geopy.distance import vincenty

# dictionary building
from collections import defaultdict

#datatime parsing
from dateutil import parser
from datetime import datetime
import time

%matplotlib inline

In [3]:
!ls ~/Documents/UCBerkeleyMIDS/W209/rodents-nyc/data
!cd ~/Documents/UCBerkeleyMIDS/W209/rodents-nyc/data/
!pwd

311_2014_first2000.csv
DOITT_SUBWAY_STATION_01_13SEPT2010.csv
Rodent_Inspection.csv
activate_rat_by_boro_date.csv
active_rat_by_zip.csv
active_rat_seasonal.csv
active_rodent_inspections.csv
all_mta.csv
mta_sightings_only.csv
rest_food_type_avg_violation.csv
restaurant_and_avg_rat_sightings.csv
restaurant_and_avg_rat_sightings_year.csv
rodent_restaurant_ratings.csv
stations_lines_colors.csv
subway_stations_with_zip.csv
subway_stations_with_zip.tsv
subway_stations_with_zip_tab.tsv
test_trimmed_311_2014.csv
trimmed_mta.csv
trimmed_mta_only.csv
year_over_year_diff_by_zip.csv
/Users/ChrisD/Documents/UCBerkeleyMIDS/W209/rodents-nyc


In [4]:
active_rodent_inspections=pd.read_csv("data/active_rodent_inspections.csv",header=0)

In [5]:
test_active_rodent_inspections=active_rodent_inspections.head(20)

In [6]:
test_active_rodent_inspections.columns

Index(['INSPECTION_TYPE', 'JOB_TICKET_OR_WORK_ORDER_ID', 'JOB_ID',
       'JOB_PROGRESS', 'BBL', 'BORO_CODE', 'BLOCK', 'LOT', 'HOUSE_NUMBER',
       'STREET_NAME', 'ZIP_CODE', 'X_COORD', 'Y_COORD', 'LATITUDE',
       'LONGITUDE', 'BOROUGH', 'INSPECTION_DATE', 'RESULT', 'APPROVED_DATE',
       'LOCATION', 'n_prev_visits', 'new_visit'],
      dtype='object')

In [7]:
test_active_rodent_inspections.head(2)

INSPECTION_TYPE  JOB_TICKET_OR_WORK_ORDER_ID   JOB_ID  JOB_PROGRESS  \
0      COMPLIANCE                        20090  PO14874             2   
1      COMPLIANCE                        24538  PO17193             2   

          BBL  BORO_CODE  BLOCK  LOT HOUSE_NUMBER        STREET_NAME  \
0  3001480046          3    148   46           81  WILLOUGHBY STREET   
1  4123940091          4  12394   91       172-04   LINDEN BOULEVARD   

     ...      Y_COORD   LATITUDE  LONGITUDE   BOROUGH      INSPECTION_DATE  \
0    ...     191458.0  40.692184 -73.985753  Brooklyn  2010-05-14 13:46:39   
1    ...     191395.0  40.691804 -73.777942    Queens  2010-03-03 09:21:09   

             RESULT        APPROVED_DATE  \
0  Active Rat Signs  2010-05-18 13:00:01   
1  Active Rat Signs  2010-03-05 11:30:16   

                                LOCATION n_prev_visits new_visit  
0  (40.6921838341671, -73.9857525784075)             2      True  
1  (40.6918037759981, -73.7779418602477)             0     False  

[2 rows x 22 columns]

### Create Subway station data and dictionary

In [8]:
subway_stations=pd.read_csv('~/Documents/UCBerkeleyMIDS/W209/rodents-nyc/data/subway_stations_with_zip.csv',header=0,dtype={'zip':str,'line':str})

#drop unneeded cols
subway_stations=subway_stations.drop(['URL','NOTES'],axis=1)
subway_stations.head(2)

#change col name
subway_stations.columns=['STATIONID', 'NAME', 'GPS', 'LINE', 'ZIP']

#format text of GPS
subway_stations['GPS']=subway_stations['GPS'].map(lambda x: x.lstrip('POINT ').replace(' ',','))
subway_stations['GPS']=subway_stations['GPS'].map(lambda x: eval(x))

In [9]:
subway_stations.head(2)

STATIONID      NAME                                      GPS  \
0          1  Astor Pl  (-73.99106999861966, 40.73005400028978)   
1          2  Canal St  (-74.00019299927328, 40.71880300107709)   

            LINE    ZIP  
0  4-6-6 Express  10003  
1  4-6-6 Express  10013

In [20]:
#Create dictionary of every GPS point associated with a station (line agnostic)

from collections import defaultdict
subway_dict=defaultdict(list)

for index, row in subway_stations.iterrows():
    #use string of STATION ID for consistency
    subway_dict[str(row['STATIONID'])]={'NAME':row['NAME'],'GPS':row['GPS']}

In [23]:
subway_dict['43']

{'GPS': (-73.89306639507903, 40.823976841237396), 'NAME': 'Simpson St'}

In [30]:
for key,value in subway_dict.items():
    if 'Canal' in subway_dict[key]['NAME']:
        print(subway_dict[key]['NAME'],':',subway_dict[key]['GPS'])

Canal St : (-74.00019299927328, 40.71880300107709)
Canal St : (-74.0062770001748, 40.72285399778783)
Canal St - Holland Tunnel : (-74.0052290023424, 40.72082400007119)
Canal St : (-73.99982638545937, 40.71817387697391)
Canal St : (-74.0018260000577, 40.71946500105898)
Canal St : (-74.00105471306033, 40.718814263587134)


In [75]:

newport_ri = (41.49008, -71.312796)
cleveland_oh = (41.499498, -81.695391)
print(great_circle(newport_ri, cleveland_oh).meters-vincenty(newport_ri, cleveland_oh).meters)

-2240.9385617375374


In [35]:
print(type(subway_stations['GPS'][0]))
subway_stations['GPS'][0]

<class 'tuple'>


(-73.99106999861966, 40.73005400028978)

## DISTANCE TESTING

In [37]:
test_active_rodent_inspections.head(2)

INSPECTION_TYPE  JOB_TICKET_OR_WORK_ORDER_ID   JOB_ID  JOB_PROGRESS  \
0      COMPLIANCE                        20090  PO14874             2   
1      COMPLIANCE                        24538  PO17193             2   

          BBL  BORO_CODE  BLOCK  LOT HOUSE_NUMBER        STREET_NAME  \
0  3001480046          3    148   46           81  WILLOUGHBY STREET   
1  4123940091          4  12394   91       172-04   LINDEN BOULEVARD   

     ...      Y_COORD   LATITUDE  LONGITUDE   BOROUGH      INSPECTION_DATE  \
0    ...     191458.0  40.692184 -73.985753  Brooklyn  2010-05-14 13:46:39   
1    ...     191395.0  40.691804 -73.777942    Queens  2010-03-03 09:21:09   

             RESULT        APPROVED_DATE  \
0  Active Rat Signs  2010-05-18 13:00:01   
1  Active Rat Signs  2010-03-05 11:30:16   

                                LOCATION n_prev_visits new_visit  
0  (40.6921838341671, -73.9857525784075)             2      True  
1  (40.6918037759981, -73.7779418602477)             0     False  

[2 rows x 22 columns]

In [44]:
for index, row in test_active_rodent_inspections.iterrows():
    #test_point=(row["LONGITUDE"],row["LATITUDE"])
    test_point=row['LOCATION']
    
    for key in subway_dict.keys():
        points=subway_dict[key]['GPS']
        
        for p in [points]:
            #long_mta=p[0]  #station longitude point to test
            #lat_mta=p[1] # station latitude point to test
            #print(p[0])
            if vincenty(test_point, (p[1],p[0])).meters <=100:
                print("index:",index,'Station ID:',key,p,subway_dict[key]['NAME'])

index: 0 Station ID: 377 (-73.98605667854612, 40.69225539645323) Jay St - MetroTech
index: 14 Station ID: 377 (-73.98605667854612, 40.69225539645323) Jay St - MetroTech


In [228]:
for key in subway_dict.keys():
        points=subway_dict[key]['GPS']
        
        for p in [points]:
            #long_mta=p[0]  #station longitude point to test
            #lat_mta=p[1] # station latitude point to test
            #print(p[0])
            if vincenty(test_point, (p[1],p[0])).meters <=100:
                print("index:",index,'Station ID:',key,p,subway_dict[key]['NAME'])

In [55]:
def MTA_distance(subway_dict,test_point,distance):
    
    stations=list()
    
    for key in subway_dict.keys():
        p=subway_dict[key]['GPS']  # gps point associated with MTA station ID
        
        
        if vincenty(test_point, (p[1],p[0])).meters <=distance:   # note that dict() in (long,lat) so easier to reverse it
                stations.append(key)  
                
    if len(stations)>0:
        return stations
    else:
        return '_'

#### Map on Test Set

In [54]:
print('unique station id:',len(subway_stations.STATIONID.unique()))
print('unique GPS:',len(subway_stations.GPS.unique()))
print('unique NAME:',len(subway_stations.NAME.unique()))

unique station id: 473
unique GPS: 473
unique NAME: 355


In [47]:
test_active_rodent_inspections.head(2)

INSPECTION_TYPE  JOB_TICKET_OR_WORK_ORDER_ID   JOB_ID  JOB_PROGRESS  \
0      COMPLIANCE                        20090  PO14874             2   
1      COMPLIANCE                        24538  PO17193             2   

          BBL  BORO_CODE  BLOCK  LOT HOUSE_NUMBER        STREET_NAME  \
0  3001480046          3    148   46           81  WILLOUGHBY STREET   
1  4123940091          4  12394   91       172-04   LINDEN BOULEVARD   

     ...      Y_COORD   LATITUDE  LONGITUDE   BOROUGH      INSPECTION_DATE  \
0    ...     191458.0  40.692184 -73.985753  Brooklyn  2010-05-14 13:46:39   
1    ...     191395.0  40.691804 -73.777942    Queens  2010-03-03 09:21:09   

             RESULT        APPROVED_DATE  \
0  Active Rat Signs  2010-05-18 13:00:01   
1  Active Rat Signs  2010-03-05 11:30:16   

                                LOCATION n_prev_visits new_visit  
0  (40.6921838341671, -73.9857525784075)             2      True  
1  (40.6918037759981, -73.7779418602477)             0     False  

[2 rows x 22 columns]

In [56]:
test_active_rodent_inspections["MTA_ID"]=test_active_rodent_inspections['LOCATION'].map(lambda x: MTA_distance(subway_dict,x,100))

/Users/ChrisD/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [58]:
test_active_rodent_inspections[test_active_rodent_inspections['MTA_ID'] != '_']

INSPECTION_TYPE  JOB_TICKET_OR_WORK_ORDER_ID   JOB_ID  JOB_PROGRESS  \
0       COMPLIANCE                        20090  PO14874             2   
14      COMPLIANCE                        28921  PO11761             2   

           BBL  BORO_CODE  BLOCK  LOT HOUSE_NUMBER        STREET_NAME  ...    \
0   3001480046          3    148   46           81  WILLOUGHBY STREET  ...     
14  3001520118          3    152  118          141    LAWRENCE STREET  ...     

     LATITUDE  LONGITUDE   BOROUGH      INSPECTION_DATE            RESULT  \
0   40.692184 -73.985753  Brooklyn  2010-05-14 13:46:39  Active Rat Signs   
14  40.691739 -73.986283  Brooklyn  2010-05-14 12:15:33  Active Rat Signs   

          APPROVED_DATE                               LOCATION n_prev_visits  \
0   2010-05-18 13:00:01  (40.6921838341671, -73.9857525784075)             2   
14  2010-05-18 13:00:33  (40.6917392459776, -73.9862827561782)             2   

   new_visit MTA_ID  
0       True  [377]  
14      True  [377]  

[2 rows x 23 columns]

#### Test on 1500 for time

In [61]:
test_1500=active_rodent_inspections.head(1500)

In [67]:
start=time.time()
test_1500["MTA_ID"]=test_1500['LOCATION'].map(lambda x: MTA_distance(subway_dict,x,100))
print(time.time()-start)

38.28602695465088


/Users/ChrisD/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [70]:
test_1500.tail(2)

INSPECTION_TYPE  JOB_TICKET_OR_WORK_ORDER_ID   JOB_ID  JOB_PROGRESS  \
1498      COMPLIANCE                        61698  PO57904             2   
1499      COMPLIANCE                        61715  PO54658             2   

             BBL  BORO_CODE  BLOCK  LOT HOUSE_NUMBER     STREET_NAME  ...    \
1498  1005280035          1    528   35           40  DOWNING STREET  ...     
1499  5028940001          5   2894    1          231  STEUBEN STREET  ...     

       LATITUDE  LONGITUDE        BOROUGH      INSPECTION_DATE  \
1498  40.729203 -74.004092      Manhattan  2010-03-03 09:58:41   
1499  40.608398 -74.082330  Staten Island  2010-03-04 14:50:00   

                RESULT        APPROVED_DATE  \
1498  Active Rat Signs  2010-03-08 13:36:16   
1499  Active Rat Signs  2010-03-17 14:23:50   

                                   LOCATION n_prev_visits new_visit MTA_ID  
1498  (40.7292032547709, -74.0040915088407)             1      True      _  
1499  (40.6083981897965, -74.0823303833877)             2      True      _  

[2 rows x 23 columns]

#### Full dataset

In [71]:
all_mta_ID=active_rodent_inspections

In [72]:
start=time.time()
all_mta_ID['MTA']=all_mta_ID['LOCATION'].map(lambda x: MTA_distance(subway_dict,x,100))
print(time.time()-start)

all_mta_ID.to_csv('all_mta_ID.csv')
all_mta_ID.to_csv('data/all_mta_ID.csv')

4032.138792991638


**took 4023 seconds overnight on local laptop**

In [75]:
all_mta_ID.head(2)

INSPECTION_TYPE  JOB_TICKET_OR_WORK_ORDER_ID   JOB_ID  JOB_PROGRESS  \
0      COMPLIANCE                        20090  PO14874             2   
1      COMPLIANCE                        24538  PO17193             2   

          BBL  BORO_CODE  BLOCK  LOT HOUSE_NUMBER        STREET_NAME  ...    \
0  3001480046          3    148   46           81  WILLOUGHBY STREET  ...     
1  4123940091          4  12394   91       172-04   LINDEN BOULEVARD  ...     

    LATITUDE  LONGITUDE   BOROUGH      INSPECTION_DATE            RESULT  \
0  40.692184 -73.985753  Brooklyn  2010-05-14 13:46:39  Active Rat Signs   
1  40.691804 -73.777942    Queens  2010-03-03 09:21:09  Active Rat Signs   

         APPROVED_DATE                               LOCATION n_prev_visits  \
0  2010-05-18 13:00:01  (40.6921838341671, -73.9857525784075)             2   
1  2010-03-05 11:30:16  (40.6918037759981, -73.7779418602477)             0   

  new_visit    MTA  
0      True  [377]  
1     False      _  

[2 rows x 23 columns]

In [74]:
mta_ID_only=all_mta_ID[all_mta_ID['MTA']!='_'] #drop rows not 100m from subway station

mta_ID_only['MTA']=mta_ID_only['MTA'].map(lambda x: list(set(x))) #remove duplicates in list

mta_ID_only.to_csv('data/mta_ID_only.csv')
mta_ID_only.shape

/Users/ChrisD/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


(10123, 23)

In [78]:
mta_ID_only[mta_ID_only['MTA'].map(lambda x:len(x)>1)].head(20)

INSPECTION_TYPE  JOB_TICKET_OR_WORK_ORDER_ID   JOB_ID  JOB_PROGRESS  \
121       COMPLIANCE                        38481  PO16845             2   
394       COMPLIANCE                        42713  PO39952             2   
463       COMPLIANCE                        42970  PO23875             2   
1096      COMPLIANCE                        54587  PO50634             1   
1105      COMPLIANCE                        54957  PO46945             2   
1107      COMPLIANCE                        54961  PO46982             2   
1129      COMPLIANCE                        55034  PO46926             2   
1161      COMPLIANCE                        55756  PO50142             2   
1234      COMPLIANCE                        56978  PO50075             2   
1337      COMPLIANCE                        59924  PO55594             2   
1338      COMPLIANCE                        59925  PO55600             2   
1452      COMPLIANCE                        61258  PO48384             2   
1464      COMPLIANCE                        61282  PO57228             2   
1491      COMPLIANCE                        61686  PO56731             2   
1536      COMPLIANCE                        62248  PO59855             1   
1665      COMPLIANCE                        65151  PO55611             2   
1710      COMPLIANCE                        65966  PO62031             2   
1712      COMPLIANCE                        65968  PO62035             2   
1717      COMPLIANCE                        66110  PO64093             1   
1782      COMPLIANCE                        68750  PO62066             2   

             BBL  BORO_CODE  BLOCK  LOT HOUSE_NUMBER           STREET_NAME  \
121   1007910032          1    791   32          113        WEST 15 STREET   
394   4012840069          4   1284   69        37-66             74 STREET   
463   2024840009          2   2484    9          880          RIVER AVENUE   
1096  1000530039          1     53   39           96      GREENWICH STREET   
1105  1000190024          1     19   24           50         TRINITY PLACE   
1107  1000530037          1     53   37          102      GREENWICH STREET   
1129  1000490001          1     49    1           75              BROADWAY   
1161  1001330019          1    133   19           57         WARREN STREET   
1234  1001940036          1    194   36          413              BROADWAY   
1337  1002080019          1    208   19          239          CANAL STREET   
1338  1002080020          1    208   20          243          CANAL STREET   
1452  4034440039          4   3444   39          325        WYCKOFF AVENUE   
1464  4034440033          4   3444   33          339        WYCKOFF AVENUE   
1491  1002350029          1    235   29          217         HESTER STREET   
1536  1000530038          1     53   38           98      GREENWICH STREET   
1665  1002090001          1    209    1          418              BROADWAY   
1710  1005920015          1    592   15          108  WEST WASHINGTON PLCE   
1712  1005920010          1    592   10          118  WEST WASHINGTON PLCE   
1717  4012850071          4   1285   71        74-15      ROOSEVELT AVENUE   
1782  1005920075          1    592   75          115  WEST WASHINGTON PLCE   

          ...         LATITUDE  LONGITUDE    BOROUGH      INSPECTION_DATE  \
121       ...        40.738341 -73.997012  Manhattan  2010-01-23 08:00:42   
394       ...        40.747183 -73.891508     Queens  2010-01-27 11:20:35   
463       ...        40.828333 -73.925625      Bronx  2010-02-01 14:20:56   
1096      ...        40.708142 -74.013526  Manhattan  2010-02-04 18:56:35   
1105      ...        40.707632 -74.013068  Manhattan  2010-02-02 17:00:24   
1107      ...        40.708320 -74.013450  Manhattan  2010-02-04 18:34:54   
1129      ...        40.707500 -74.011917  Manhattan  2010-02-02 17:20:26   
1161      ...        40.714757 -74.009281  Manhattan  2010-02-05 18:24:21   
1234      ...        40.719078 -74.002168  Manhattan  2010-03-09 10:44:42   

In [79]:
print(mta_ID_only.shape[0])
print(mta_ID_only[mta_ID_only['MTA'].map(lambda x:len(x)>1)].shape[0])
427/10123

10123
427


0.04218117158944977

Of the 10123 MTA station-adjacent sightings, 427 could be double-counted because they are between two close stations, about 4.2% of the sightings. We will count them as belonging to either station because the audience will be looking at the data on a per-station basis, not as a statistically exact represenation of rat sighting probabilities. 

#### Getting Lines and Colors

In [80]:
subway_stations.head(2)

STATIONID      NAME                                      GPS  \
0          1  Astor Pl  (-73.99106999861966, 40.73005400028978)   
1          2  Canal St  (-74.00019299927328, 40.71880300107709)   

            LINE    ZIP  
0  4-6-6 Express  10003  
1  4-6-6 Express  10013

In [81]:
subway_stations_lines_colors=subway_stations

In [82]:
subway_stations_lines_colors['LINES']=subway_stations_lines_colors['LINE'].map(lambda x: x.split('-'))

In [ ]:

Primary Trunk line	Color[12][13]	Pantone[14]	Hexadecimal	Service bullets
IND Eighth Avenue Line	Vivid blue	PMS 286	#2850ad	"A" train ​"C" train ​"E" train
IND Sixth Avenue Line	Bright orange	PMS 165	#ff6319	"B" train ​"D" train ​"F" train ​"M" train
IND Crosstown Line	Lime green	PMS 376	#6cbe45	"G" train
BMT Canarsie Line	Light slate gray	50% black	#a7a9ac	"L" train
BMT Nassau Street Line	Terra cotta brown	PMS 154	#996633	"J" train ​"Z" train
BMT Broadway Line	Sunflower yellow	PMS 116	#fccc0a	"N" train ​"Q" train ​"R" train ​"W" train
IRT Broadway–Seventh Avenue Line	Tomato red	PMS 185	#ee352e	"1" train ​"2" train ​"3" train
IRT Lexington Avenue Line	Apple green	PMS 355	#00933c	"4" train ​"5" train ​"6" train "6" express train
IRT Flushing Line	Raspberry	PMS Purple	#b933ad	"7" train "7" express train​
Shuttles	Dark slate gray	70% black	#808183	shuttle train

In [83]:
subway_colors={'blue':['A','C','E'],'orange':['B','D','F','M'],'lime':['G'], \
              'grey':['L'],'brown':['J','Z'],'yellow':['N','Q','R','W'], \
              'red':['1','2','3'],'green':['4','5','6','6 Express'],'purple':['7','7 Express'],\
              'silver':['S']}

In [84]:
subway_line_to_color=dict()

for key,value in subway_colors.items():
    for v in value:
        subway_line_to_color[v]=key

In [85]:
lines=list()

for index,row in subway_stations_lines_colors.iterrows():
    
    for L in row['LINES']:
        if L in lines:
            pass
        else:
            lines.append(L)

print(lines)

['4', '6', '6 Express', '1', '2', '3', 'A', 'B', 'C', 'E', 'M', 'R', 'J', 'Z', 'D', 'N', 'Q', 'S', '5', '7', '7 Express', 'F', 'G', 'L', 'W']


In [86]:
subway_stations_lines_colors['COLOR']=None
subway_stations_lines_colors.head(2)

STATIONID      NAME                                      GPS  \
0          1  Astor Pl  (-73.99106999861966, 40.73005400028978)   
1          2  Canal St  (-74.00019299927328, 40.71880300107709)   

            LINE    ZIP              LINES COLOR  
0  4-6-6 Express  10003  [4, 6, 6 Express]  None  
1  4-6-6 Express  10013  [4, 6, 6 Express]  None

In [87]:
# Make colors column

for index,row in subway_stations_lines_colors.iterrows():
    
    colors=list()
    
    for L in row['LINES']:
        c=subway_line_to_color[L]  #lookup color of subway line
        
        if c not in colors:
            #print('hi')
            colors.append(c)
    
    subway_stations_lines_colors['COLOR'].iloc[index]=colors
    #print(colors, row['COLOR'])

subway_stations_lines_colors.head(2)

/Users/ChrisD/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:194: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


STATIONID      NAME                                      GPS  \
0          1  Astor Pl  (-73.99106999861966, 40.73005400028978)   
1          2  Canal St  (-74.00019299927328, 40.71880300107709)   

            LINE    ZIP              LINES    COLOR  
0  4-6-6 Express  10003  [4, 6, 6 Express]  [green]  
1  4-6-6 Express  10013  [4, 6, 6 Express]  [green]

In [88]:
subway_stations_lines_colors.head(20)

STATIONID                       NAME  \
0           1                   Astor Pl   
1           2                   Canal St   
2           3                    50th St   
3           4                  Bergen St   
4           5           Pennsylvania Ave   
5           6                   238th St   
6           7  Cathedral Pkwy (110th St)   
7           8     Kingston - Throop Aves   
8           9                    65th St   
9          10                    36th St   
10         11     Delancey St - Essex St   
11         12             Van Siclen Ave   
12         13                Norwood Ave   
13         14            104th-102nd Sts   
14         15                 DeKalb Ave   
15         16             Beach 105th St   
16         17              Beach 90th St   
17         18                 Freeman St   
18         19              Intervale Ave   
19         20            182nd-183rd Sts   

                                         GPS           LINE    ZIP  \
0    (-73.99106999861966, 40.73005400028978)  4-6-6 Express  10003   
1    (-74.00019299927328, 40.71880300107709)  4-6-6 Express  10013   
2    (-73.98384899986625, 40.76172799961419)            1-2  10019   
3    (-73.97499915116808, 40.68086213682956)          2-3-4  11217   
4    (-73.89488591154061, 40.66471445143568)            3-4  11207   
5    (-73.90087000018522, 40.88466700064975)              1  10463   
6   (-73.95806670661364, 40.800581558114956)          A-B-C  10036   
7    (-73.94085899871263, 40.67991899941601)            A-C  11216   
8     (-73.8987883783301, 40.74971952935675)          E-M-R  11377   
9    (-73.92901818461539, 40.75196004401078)          E-M-R  11101   
10   (-73.98740940202974, 40.71830605618619)          J-M-Z  10002   
11   (-73.89165772702445, 40.67802821447783)            J-Z  11207   
12   (-73.87962599910783, 40.68152000045683)            J-Z  11208   
13   (-73.84443500029684, 40.69516599823373)            J-Z  11418   
14  (-73.98177094440949, 40.690648119969794)      B-D-N-Q-R  11201   
15   (-73.82758075034528, 40.58326843810286)            A-S  11694   
16   (-73.81365140419632, 40.58809156457325)            A-S  11693   
17  (-73.89175225349464, 40.829987446384116)            2-5  10459   
18  (-73.89661738461646, 40.822142131170786)            2-5  10459   
19   (-73.90074099998965, 40.85609299881864)            B-D  10457   

                LINES                   COLOR  
0   [4, 6, 6 Express]                 [green]  
1   [4, 6, 6 Express]                 [green]  
2              [1, 2]                   [red]  
3           [2, 3, 4]            [red, green]  
4              [3, 4]            [red, green]  
5                 [1]                   [red]  
6           [A, B, C]          [blue, orange]  
7              [A, C]                  [blue]  
8           [E, M, R]  [blue, orange, yellow]  
9           [E, M, R]  [blue, orange, yellow]  
10          [J, M, Z]         [brown, orange]  
11             [J, Z]                 [brown]  
12             [J, Z]                 [brown]  
13             [J, Z]                 [brown]  
14    [B, D, N, Q, R]        [orange, yellow]  
15             [A, S]          [blue, silver]  
16             [A, S]          [blue, silver]  
17             [2, 5]            [red, green]  
18             [2, 5]            [red, green]  
19             [B, D]                [orange]

In [89]:
subway_stations_lines_colors.to_csv('data/stations_lines_colors.csv')
!head data/stations_lines_colors.csv

,STATIONID,NAME,GPS,LINE,ZIP,LINES,COLOR
0,1,Astor Pl,"(-73.99106999861966, 40.73005400028978)",4-6-6 Express,10003,"['4', '6', '6 Express']",['green']
1,2,Canal St,"(-74.00019299927328, 40.71880300107709)",4-6-6 Express,10013,"['4', '6', '6 Express']",['green']
2,3,50th St,"(-73.98384899986625, 40.76172799961419)",1-2,10019,"['1', '2']",['red']
3,4,Bergen St,"(-73.97499915116808, 40.68086213682956)",2-3-4,11217,"['2', '3', '4']","['red', 'green']"
4,5,Pennsylvania Ave,"(-73.89488591154061, 40.66471445143568)",3-4,11207,"['3', '4']","['red', 'green']"
5,6,238th St,"(-73.90087000018522, 40.88466700064975)",1,10463,['1'],['red']
6,7,Cathedral Pkwy (110th St),"(-73.95806670661364, 40.800581558114956)",A-B-C,10036,"['A', 'B', 'C']","['blue', 'orange']"
7,8,Kingston - Throop Aves,"(-73.94085899871263, 40.67991899941601)",A-C,11216,"['A', 'C']",['blue']
8,9,65th St,"(-73.8987883783301, 40.74971952935675)",E-M-R,11377,"['E', 'M', 'R']","['blue', 'orange', 'yellow']"


In [94]:
subway_stations_lines_colors

subway_stations_lines_colors.index[subway_stations_lines_colors['NAME']=='103rd St']

Int64Index([158, 160, 457], dtype='int64')

### Add lines and colors

In [96]:
print('total',mta_ID_only.shape[0])

print('JOB_ID',len(mta_ID_only['JOB_ID'].unique()))
print('JOB_TICKET_OR_WORK_ORDER_ID',len(mta_ID_only['JOB_TICKET_OR_WORK_ORDER_ID'].unique()))
print('BBL',len(mta_ID_only['BBL'].unique()))


total 10123
JOB_ID 7040
JOB_TICKET_OR_WORK_ORDER_ID 10123
BBL 3256


In [101]:
for i in mta_ID_only.columns:
    print(i, len(mta_ID_only[i].unique()) )

INSPECTION_TYPE 2
JOB_TICKET_OR_WORK_ORDER_ID 10123
JOB_ID 7040
JOB_PROGRESS 21
BBL 3256
BORO_CODE 4
BLOCK 976
LOT 195
HOUSE_NUMBER 1888
STREET_NAME 851
ZIP_CODE 115
X_COORD 4224
Y_COORD 4333
LATITUDE 4972
LONGITUDE 5091
BOROUGH 4
INSPECTION_DATE 10122
RESULT 1
APPROVED_DATE 8652
LOCATION 5115
n_prev_visits 30
new_visit 2


TypeError: unhashable type: 'list'

In [102]:
newcols= ['JOB_TICKET_OR_WORK_ORDER_ID','BORO_CODE', 'BOROUGH', 'ZIP_CODE', 'LATITUDE',
       'LONGITUDE', 'INSPECTION_DATE', 'APPROVED_DATE',
       'LOCATION', 'n_prev_visits', 'new_visit', 'MTA']

In [103]:
trimmed_mta_ID_only=mta_ID_only[newcols]

In [104]:
trimmed_mta_ID_only.to_csv('data/trimmed_mta.csv')

In [455]:
trimmed_mta_ID_only['COLOR']='-'
trimmed_mta_ID_only['LINES']='-'

/Users/ChrisD/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/ChrisD/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [119]:
subway_stations_lines_colors.index[subway_stations_lines_colors['STATIONID']==3][0]

2

In [125]:
type(trimmed_mta_ID_only['MTA'].iloc[3][0])

str

In [131]:
subway_stations_lines_colors['STATIONID']==3

0      False
1      False
2       True
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...  
443    False
444    False
445    False
446    False
447    False
448    False
449    False
450    False
451    False
452    False
453    False
454    False
455    False
456    False
457    False
458    False
459    False
460    False
461    False
462    False
463    False
464    False
465    False
466    False
467    False
468    False
469    False
470    False
471    False
472    False
Name: STATIONID, Length: 473, dtype: bool

In [132]:
def get_mta_color(ID,subway_df):
    
    color=list() #initiate colors
    
    for idee in ID:
        
        #find index of subway station
        stat_index=subway_df.index[subway_df['STATIONID']==int(idee)][0]
        
        # append lists with lines and colors
        for c in subway_df['COLOR'].iloc[stat_index]:
            color.append(c)
            
    return color

        
def get_mta_lines(ID,subway_df):
    
    lines=list() #initiate colors
    
    for idee in ID:
        
        #find index of subway station
        stat_index=subway_df.index[subway_df['STATIONID']==int(idee)][0]
        
        # append lists with lines and colors
        for L in subway_df['LINES'].iloc[stat_index]:
            lines.append(L)
            
    return lines        

In [133]:
trimmed_mta_ID_only['COLOR']=trimmed_mta_ID_only['MTA'].map(lambda x: get_mta_color(x,subway_stations_lines_colors))
trimmed_mta_ID_only['LINES']=trimmed_mta_ID_only['MTA'].map(lambda x: get_mta_lines(x,subway_stations_lines_colors))

/Users/ChrisD/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/ChrisD/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [136]:
trimmed_mta_ID_only.head(5)

JOB_TICKET_OR_WORK_ORDER_ID  BORO_CODE    BOROUGH  ZIP_CODE   LATITUDE  \
0                         20090          3   Brooklyn     11201  40.692184   
14                        28921          3   Brooklyn     11201  40.691739   
31                        31318          3   Brooklyn     11225  40.669580   
32                        31320          3   Brooklyn     11225  40.669443   
36                        32176          1  Manhattan     10029  40.795130   

    LONGITUDE      INSPECTION_DATE        APPROVED_DATE  \
0  -73.985753  2010-05-14 13:46:39  2010-05-18 13:00:01   
14 -73.986283  2010-05-14 12:15:33  2010-05-18 13:00:33   
31 -73.951250  2010-01-27 08:41:55  2010-01-27 11:02:25   
32 -73.951189  2010-01-27 09:08:07  2010-01-27 11:03:32   
36 -73.944859  2010-01-20 17:19:09  2010-01-22 13:22:12   

                                 LOCATION  n_prev_visits  new_visit    MTA  \
0   (40.6921838341671, -73.9857525784075)              2       True  [377]   
14  (40.6917392459776, -73.9862827561782)              2       True  [377]   
31  (40.6695801910464, -73.9512497520348)              0      False  [445]   
32  (40.6694429266035, -73.9511885678396)              0      False  [445]   
36  (40.7951302785112, -73.9448588661273)              0      False  [450]   

           COLOR              LINES  
0       [yellow]             [N, R]  
14      [yellow]             [N, R]  
31  [red, green]             [3, 4]  
32  [red, green]             [3, 4]  
36       [green]  [4, 6, 6 Express]

In [137]:
trimmed_mta_ID_only.to_csv('data/trimmed_mta_ID_only.csv')

In [140]:
trimmed_mta_ID_only['YEAR_INSPEC']=trimmed_mta_ID_only['INSPECTION_DATE'].map(lambda x:parser.parse(x).year)
trimmed_mta_ID_only['MONTH_INSPEC']=trimmed_mta_ID_only['INSPECTION_DATE'].map(lambda x:parser.parse(x).month)

/Users/ChrisD/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Users/ChrisD/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [141]:
trimmed_mta_ID_only.shape[0]

10123

### Final separate out stations for Groupby

In [142]:
station_trimmed=trimmed_mta_ID_only

In [147]:
s = station_trimmed.apply(lambda x: pd.Series(x['MTA']),axis=1).stack().reset_index(level=1, drop=True)
s.name = 'MTA_sep'

station_trimmed=station_trimmed.drop('MTA', axis=1).join(s)

In [148]:
station_group=station_trimmed

In [149]:
#dummy=station_group.groupby(['MTA_sep','YEAR_INSPEC','MONTH_INSPEC']).count()
dummy=station_group.groupby(['MTA_sep','YEAR_INSPEC','MONTH_INSPEC']).count()

In [151]:
dummy.head(2)

JOB_TICKET_OR_WORK_ORDER_ID  BORO_CODE  \
MTA_sep YEAR_INSPEC MONTH_INSPEC                                           
1       2010        5                                       1          1   
        2011        2                                       1          1   

                                  BOROUGH  ZIP_CODE  LATITUDE  LONGITUDE  \
MTA_sep YEAR_INSPEC MONTH_INSPEC                                           
1       2010        5                   1         1         1          1   
        2011        2                   1         1         1          1   

                                  INSPECTION_DATE  APPROVED_DATE  LOCATION  \
MTA_sep YEAR_INSPEC MONTH_INSPEC                                             
1       2010        5                           1              1         1   
        2011        2                           1              1         1   

                                  n_prev_visits  new_visit  COLOR  LINES  
MTA_sep YEAR_INSPEC MONTH_INSPEC                                          
1       2010        5                         1          1      1      1  
        2011        2                         1          1      1      1

In [226]:
# by year and month, grouped by station
grouped_df = station_group.groupby(['MTA_sep','YEAR_INSPEC','MONTH_INSPEC'])
mta_year_month=pd.DataFrame(grouped_df.size().reset_index(name = "Group_Count"))
#mta_year_month['COLOR']='-'
#mta_year_month['LINES']='-'
#get color
mta_year_month['COLOR']=mta_year_month['MTA_sep'].map(lambda x: get_mta_color([x],subway_stations_lines_colors))
#get lines
mta_year_month['LINES']=mta_year_month['MTA_sep'].map(lambda x: get_mta_lines([x],subway_stations_lines_colors))

# by year, grouped by station
grouped_df = station_group.groupby(['MTA_sep','YEAR_INSPEC'])
mta_year=pd.DataFrame(grouped_df.size().reset_index(name = "Group_Count"))
#mta_year['COLOR']='-'
#mta_year['LINES']='-'
#get color
mta_year['COLOR']=mta_year['MTA_sep'].map(lambda x: get_mta_color([x],subway_stations_lines_colors))
#get lines
mta_year['LINES']=mta_year['MTA_sep'].map(lambda x: get_mta_lines([x],subway_stations_lines_colors))

In [227]:
mta_year.head(10)
#mta_year.shape[0]

MTA_sep  YEAR_INSPEC  Group_Count     COLOR              LINES
0       1         2010            1   [green]  [4, 6, 6 Express]
1       1         2011            2   [green]  [4, 6, 6 Express]
2       1         2015            1   [green]  [4, 6, 6 Express]
3       1         2016            3   [green]  [4, 6, 6 Express]
4     100         2016            1  [yellow]                [Q]
5     100         2017            1  [yellow]                [Q]
6     101         2011            1  [purple]     [7, 7 Express]
7     101         2014            4  [purple]     [7, 7 Express]
8     101         2015            2  [purple]     [7, 7 Express]
9     101         2017            1  [purple]     [7, 7 Express]

In [228]:
print('MTA_sep type in mta_year:',type(mta_year['MTA_sep'].iloc[10]))
print('STATIONID type in subway_stations_lines_colors:',type(subway_stations_lines_colors['STATIONID'].iloc[10]))

MTA_sep type in mta_year: <class 'str'>
STATIONID type in subway_stations_lines_colors: <class 'numpy.int64'>


In [229]:
mta_year['MTA_sep']=pd.to_numeric(mta_year['MTA_sep'])
mta_year_month['MTA_sep']=pd.to_numeric(mta_year_month['MTA_sep'])

In [230]:
#change MTA_sep ID to numeric for merge
mta_year['MTA_sep']=pd.to_numeric(mta_year['MTA_sep'])
mta_year_month['MTA_sep']=pd.to_numeric(mta_year_month['MTA_sep'])

#merge with 
mta_year=mta_year.merge(subway_stations_lines_colors, left_on='MTA_sep', right_on='STATIONID', how='inner')
mta_year_month=mta_year_month.merge(subway_stations_lines_colors, left_on='MTA_sep', right_on='STATIONID', how='inner')

#trim mta_year
mta_year=mta_year[['MTA_sep','NAME','LINE','YEAR_INSPEC','Group_Count','GPS','ZIP','LINES_y','COLOR_y']]
mta_year.columns=['MTA_ID', 'NAME', 'ROUTE', 'YEAR_INSPEC','COUNT', 'GPS', 'ZIP', 'LINES',
       'COLOR']

#trim mta_year_month
mta_year_month=mta_year_month[['MTA_sep','NAME','LINE','YEAR_INSPEC','MONTH_INSPEC','Group_Count','GPS','ZIP','LINES_y','COLOR_y']]
mta_year_month.columns=['MTA_ID', 'NAME', 'ROUTE', 'YEAR_INSPEC', 'MONTH_INSPEC','COUNT', 'GPS', 'ZIP',
       'LINES', 'COLOR']


In [231]:
mta_year.head(2)

MTA_ID      NAME          ROUTE  YEAR_INSPEC  COUNT  \
0       1  Astor Pl  4-6-6 Express         2010      1   
1       1  Astor Pl  4-6-6 Express         2011      2   

                                       GPS    ZIP              LINES    COLOR  
0  (-73.99106999861966, 40.73005400028978)  10003  [4, 6, 6 Express]  [green]  
1  (-73.99106999861966, 40.73005400028978)  10003  [4, 6, 6 Express]  [green]

##### create unique station name

In [232]:
mta_year['STATION']=mta_year['NAME'] + ' : ' + mta_year['ROUTE']
mta_year_month['STATION']=mta_year['NAME'] + ' : ' + mta_year['ROUTE']

mta_year=mta_year[['MTA_ID', 'STATION','NAME', 'ROUTE', 'YEAR_INSPEC','COUNT', 'GPS', 'ZIP',
       'LINES', 'COLOR']]
mta_year_month=mta_year_month[['MTA_ID', 'STATION','NAME', 'ROUTE', 'YEAR_INSPEC', 'MONTH_INSPEC','COUNT', 'GPS', 'ZIP',
       'LINES', 'COLOR']]

In [233]:
mta_year.head(2)

MTA_ID                   STATION      NAME          ROUTE  YEAR_INSPEC  \
0       1  Astor Pl : 4-6-6 Express  Astor Pl  4-6-6 Express         2010   
1       1  Astor Pl : 4-6-6 Express  Astor Pl  4-6-6 Express         2011   

   COUNT                                      GPS    ZIP              LINES  \
0      1  (-73.99106999861966, 40.73005400028978)  10003  [4, 6, 6 Express]   
1      2  (-73.99106999861966, 40.73005400028978)  10003  [4, 6, 6 Express]   

     COLOR  
0  [green]  
1  [green]

In [234]:
mta_year.head(20)

MTA_ID                                   STATION  \
0        1                  Astor Pl : 4-6-6 Express   
1        1                  Astor Pl : 4-6-6 Express   
2        1                  Astor Pl : 4-6-6 Express   
3        1                  Astor Pl : 4-6-6 Express   
4      100                            Ocean Pkwy : Q   
5      100                            Ocean Pkwy : Q   
6      101   Vernon Blvd - Jackson Ave : 7-7 Express   
7      101   Vernon Blvd - Jackson Ave : 7-7 Express   
8      101   Vernon Blvd - Jackson Ave : 7-7 Express   
9      101   Vernon Blvd - Jackson Ave : 7-7 Express   
10     102  68th St - Hunter College : 4-6-6 Express   
11     102  68th St - Hunter College : 4-6-6 Express   
12     103          Queensboro Plz : 7-7 Express-N-W   
13     105      Union Sq - 14th St : 4-5-6-6 Express   
14     106               Bedford - Nostrand Aves : G   
15     106               Bedford - Nostrand Aves : G   
16     106               Bedford - Nostrand Aves : G   
17     106               Bedford - Nostrand Aves : G   
18     106               Bedford - Nostrand Aves : G   
19     106               Bedford - Nostrand Aves : G   

                         NAME            ROUTE  YEAR_INSPEC  COUNT  \
0                    Astor Pl    4-6-6 Express         2010      1   
1                    Astor Pl    4-6-6 Express         2011      2   
2                    Astor Pl    4-6-6 Express         2015      1   
3                    Astor Pl    4-6-6 Express         2016      3   
4                  Ocean Pkwy                Q         2016      1   
5                  Ocean Pkwy                Q         2017      1   
6   Vernon Blvd - Jackson Ave      7-7 Express         2011      1   
7   Vernon Blvd - Jackson Ave      7-7 Express         2014      4   
8   Vernon Blvd - Jackson Ave      7-7 Express         2015      2   
9   Vernon Blvd - Jackson Ave      7-7 Express         2017      1   
10   68th St - Hunter College    4-6-6 Express         2013      1   
11   68th St - Hunter College    4-6-6 Express         2017      4   
12             Queensboro Plz  7-7 Express-N-W         2014      2   
13         Union Sq - 14th St  4-5-6-6 Express         2015      2   
14    Bedford - Nostrand Aves                G         2010     32   
15    Bedford - Nostrand Aves                G         2011     30   
16    Bedford - Nostrand Aves                G         2012     16   
17    Bedford - Nostrand Aves                G         2013      1   
18    Bedford - Nostrand Aves                G         2014     11   
19    Bedford - Nostrand Aves                G         2015      3   

                                         GPS    ZIP                 LINES  \
0    (-73.99106999861966, 40.73005400028978)  10003     [4, 6, 6 Express]   
1    (-73.99106999861966, 40.73005400028978)  10003     [4, 6, 6 Express]   
2    (-73.99106999861966, 40.73005400028978)  10003     [4, 6, 6 Express]   
3    (-73.99106999861966, 40.73005400028978)  10003     [4, 6, 6 Express]   
4    (-73.96850099975177, 40.57631166708091)  11235                   [Q]   
5    (-73.96850099975177, 40.57631166708091)  11235                   [Q]   
6    (-73.95358099875249, 40.74262599969749)  11101        [7, 7 Express]   
7    (-73.95358099875249, 40.74262599969749)  11101        [7, 7 Express]   
8    (-73.95358099875249, 40.74262599969749)  11101        [7, 7 Express]   
9    (-73.95358099875249, 40.74262599969749)  11101        [7, 7 Express]   
10   (-73.96387000158042, 40.76814100049679)  10065     [4, 6, 6 Express]   
11   (-73.96387000158042, 40.76814100049679)  10065     [4, 6, 6 Express]   
12   (-73.9401635351909, 40.750635651014804)  11101  [7, 7 Express, N, W]   
13  (-73.98995099881881, 40.734673000996125)  10003  [4, 5, 6, 6 Express]   
14   (-73.95352200064022, 40.68962700158444)  11205                   [G]   
15   (-73.95352200064022, 40.68962700158444)  11205                   [G]   
16   (-73.95352200064022, 40.68962700158444)  1

In [235]:
mta_year.to_csv('data/mta_100m_rad_year.csv')
mta_year_month.to_csv('data/mta_100m_rad_year_month.csv')